.name: Sample Reactjs
description: Sample Reactjs for Lyrid Demo
ignoreFiles:
  - .git
  - node_modules
  - build
  - .env
  - yarn.lock
  - package-lock.json
modules:
  - name: Sample Reactjs Module
    language: nodejs18.x
    web: react
    description: Sample Module for reactjs
    functions:
      - name: reactjs-entry
        entry: src/index.js
        description: Hello World
